### ISSUE TITLE
Prepare network data

### ISSUE THREAD

**Issue by yejoon-lee** [Wittgensteinian/Seoul_Metro#2]
Prepare network data using networkx. The final goal is to create an instance of nx.Graph which represents the network data of Seoul metro.

**Comment by yejoon-lee** [comment]
@MilkClouds 수고하셨습니다! 다만 두 가지만 확인 부탁드립니다!

1. 프린트된 'V: 598, E: 1360'이 각각 vertex와 edge의 개수를 의미하는 것으로 추측했습니다. 그런데 `G.number_of_edges()`를 통해 구한 값과 프린트해주신 edge의 개수가 다릅니다. 뭔가 문제가 있는 건지, 아니면 그냥 넘어가도 되는 문제인지 확인 부탁드립니다.

2. 제가 이해한 바로는, Graph의 node를 자체적으로 만드신 Station class의 instance로 설정하신 것 같습니다. 이 경우, 추후 작업이 어려워질 것 같습니다. G.adj를 Station class의 instance로 indexing해야 하는 상황이 발생하기 때문입니다.   
**Graph의 node를 string이나 int로 만들어주시면 감사하겠습니다.**
  
 
또한 주제 넘는 말일 수 있지만 두 가지만 더 부탁드리고 싶습니다.  
1. 주석 또는 마크다운 셀로 설명을 달아주시는 게 제가 코드를 읽기 훨씬 편할 것 같습니다.  
2. 코드는 최대한 쉬운 방향으로 짜주시길 부탁드립니다!!

**Comment by MilkClouds** [comment]
@Wittgensteinian 
1. Edge 수에 대한 이슈
Edge 수가 모자른 이슈는 networkx.Graph가 양방향 그래프를 나타내는 클래스여서 그렇고, networkx.DiGraph를 대신 사용함으로써 해결했습니다. 다만 그렇게 해도 "미금->정자"가 수인+분당선(K2호선)과 신분당선(D호선)의 두 가지 경로로 존재하고, 이렇게 두 역을 이동하는 호선이 두 가지 존재하는 두 역의 쌍이 14쌍 존재합니다. 이 경우 DiGraph 클래스에서 두 노드를 잇는 여러 개의 간선을 인식을 못해서(사실 호선이 달라도 간선의 역 이름과 weight가 같으므로 구분하는 의미가 있는지 모르겠긴 합니다) 간선 하나를 버려야 합니다.
그래서 현재 1. 역의 고유번호를 없애고, 역의 이름만을 채택하여 사용 2. 두 역을 이동하는 경로가 2개인 경우, 일단 간선은 하나만 만들어 두고 나중에 후처리할 때 예외처리
이렇게 구상중인데 어떠신가요? 일단 이렇게 처리해서 Commit했습니다.
2. Graph node를 string으로 만드는 이슈
Graph의 노드를 역이름, string으로 바꾸는 건 금방 구현했고, 개인적으로는 아예 역 이름뿐만 아니라 몇호선의 역인지까지 저장하게 하나의 클래스로 처리하려고 이렇게 구현했었습니다.
또한 indexing의 경우 각각의 역에 대한 Station 인스턴스를 딕셔너리 등에 저장해놓고 사용할 생각이었는데, 아무래도 직관적으로는 건의해주신 방향이 더 맞지 않을까 생각이 들어 수정했습니다.
3. 주석과 마크다운 셀 설명
주석이나 마크다운 셸로 설명을 다는 부분은 제가 늘상 개발을 혼자 하느라 미처 생각하지 못한 부분입니다. 앞으로는 유의하도록 하겠습니다.
쉬운 방향으로 짜는 것은 이 정도로도 충분히 짧고 쉬우며 효율적이라고 판단해서 이렇게 한 것이라.. 아마 주석을 잘 달아드렸으면 이해가 훨씬 쉽지 않았을까 싶습니다.




덤으로 같은 역을 이동하는 두 개의 간선이 존재하는 역의 쌍을 첨부합니다.
```
을지로4가 동대문역사문화공원
동대문역사문화공원 을지로4가
청량리 회기
회기 청량리
청량리 회기
회기 청량리
회기 중랑
중랑 회기
중랑 상봉
상봉 중랑
상봉 망우
망우 상봉
정자 미금
미금 정자
```

**Comment by yejoon-lee** [comment]
@MilkClouds 수고하셨습니다!!
제 생각에 궁극적으로는 두 가지 서로 다른 그래프를 만들 필요가 있어 보입니다.
## 1. 역명을 node로 (지하철 네트워크 구조 보존용)
- 작업해주신 코드의 첫번째 그래프의 형태입니다.
- 장점: 그래프 구조가 지하철 네트워크의 구조를 그대로 반영한다.
- 단점: 일반적인 최단거리 알고리즘으로 최단거리 계산 시 곤란해질 수 있다.

> 예를 들어, 오리 -> 판교의 경우와 오리 -> 수내의 경우를 생각해보겠습니다. 한 node에서 다른 인접한 node까지 걸리는 시간을 1, 환승 시간도 1이라고 해보겠습니다.
**실제**
오리 -> 판교: 오리(K232) -> 미금(K231) -> 정자(K230) ->정자(D12) -> 판교(D11)  
total 4
오리 -> 수내: 오리(K232) -> 미금(K231) -> 정자(K230) -> 수내(K229)  
total 3
**1번 그래프 구조 상**
오리 -> 판교: 오리 -> 미금 -> 정자 -> 판교   
total 3
오리 -> 수내: 오리 -> 미금 -> 정자 -> 판교  
total 3
즉, 환승 시간을 고려하지 않은 최단거리가 산출됩니다.
- 목적: 그래프 구조가 반영되는 분석 시 활용



### Notice
두 역 사이에 두 개의 노선이 존재하는 경우, edge를 두 개로 구현하는 것이 좋을 듯 합니다. 이는 nx.MultipDiGraph를 활용하시면 될 듯 합니다. (사실 이미 짜신 코드에서 nx.DiGrpah를 nx.MultiDiGraph로 바꾸기만 하면 되더라고요!)  


## 2. 역번호를 node로 (최단거리 계산용)
- 환승을 edge로 구현하는 방식입니다. 해당 edge의 weight는 환승 시간이 되겠죠.
- Node가 역번호이기 때문에, 환승 edge가 loop edge는 아닙니다. 예를 들면 정자(D12)와 정자(K230) 사이의 edge가 되겠죠.
- 장점: 최단거리 계산이 용이하다.
- 단점: 그래프 구조가 지하철 네트워크의 구조와 다르다.
- 목적: 노드와 노드 간 최단거리 계산

> e.g. (환승 시간을 3으로 가정)
`G.adj['D12']` 실행 시  
**원하는 결과:**  
`AtlasView({'K230': {'weight': '3'}, 'D11': {'weight': '4'}, 'D13': {'weight': '3'}})`
(D12 - 정자, K230 - 정자, D11 - 판교, D13 - 미금)

### 요청사항
**이를 구현해주시기 바랍니다.**  

## 계획
우선 저는 역명 그래프(1번 그래프)를 통해 descriptive analysis를 시작하도록 하겠습니다. 최단거리를 활용하지 않은, node나 edge, degree 등만 활용하는 분석으로 시작하겠습니다. 이후 역번호 그래프(2번 그래프)가 만들어지면 최단거리를 활용하는 분석도 시작하도록 합시다. 

**혹시 다른 생각이 있으시면 말씀해주시기 바랍니다!!**

**Comment by MilkClouds** [comment]
1번 그래프는 제안하신대로 Multi 키워드를 붙여 구현했고, 2번의 경우 사실 이미 구현이 되어 있으므로 따로 구현할 필요가 없습니다.
`stNo_to_st`는 key로 역번호를 받아 value로 Station 인스턴스를 반환하는 딕셔너리인데, 이걸 이용하면 됩니다.
예를 들어 `G.adj[stNo_to_st['D12']]` 와 같은 형식으로, `stNo=='D12'`인 역을 `stNo_to_st['D12']`를 통해 불러온 후 참조하면 됩니다.
역번호를 살리는 경우 그냥 이렇게 Station 클래스를 살려두고 역번호->Station으로 변환해주는 딕셔너리 하나를 두는 편이 더 나을 것이라 판단했습니다. 역번호, 역이름, 노선번호를 바로 알 수 있으니까요.

아, 그리고 2번 그래프에서 Station 클래스의 `__repr__` (겉으로 표시되는 문구)를 역번호와 역이름이 모두 나오게 약간 수정했습니다. 이거 말고는 고칠 게 없네요.
![image](https://user-images.githubusercontent.com/26109705/114424107-c5ed8280-9bf2-11eb-9426-477d57db5d4f.png)

**Comment by yejoon-lee** [comment]
@MilkClouds 수고하셨습니다!  
다만 저는 여전히 graph의 node를 string으로 두는 것이 편리하다고 생각합니다. Class를 활용하신 목적은 알겠으나, graph의 node가 string인 것이 이후 범용성의 측면에서 좋을 것 같습니다. 지금 @MilkClouds 님이나 저는 전처리 코드를 알고 있기 때문에 instance를 통한 indexing이 어떠한 것을 의미하는 지 압니다. 그러나 예를 들어 제 3자가 전처리의 결과물인 그래프만을 활용하려 할 때, instance를 통한 indexing을 해야 한다면 그것이 의미하는 바를 알기 위해 전처리 코드까지도 읽어 봐야 하는 상황이 발생합니다. 
역번호, 역이름, 노선번호를 바로 알 수 있는 건 좋습니다. 그러나 이는 node를 string으로 구현하더라도, 마찬가지로 dictionary를 통해 충분히 구현 가능한 기능입니다.
**Node를 Station instance 대신 string으로 두는 것에 대해 어떻게 생각하시는지 궁금합니다.**

**Comment by MilkClouds** [comment]
@Wittgensteinian String으로 노드를 수정했습니다.

**Comment by yejoon-lee** [comment]
We can close this issue with #4
